var express = require('express');
var app = express();
var multer  = require('multer');
var maxFileSize=1000000;
var upload1=multer({ limits: { fileSize: maxFileSize } }).single('file');
//Multer accepts option object {multer(option)} to specify certain conditions
//file limits,dest & others can be passed as keys in option object

app.set('port',process.env.PORT||3000);

app.get('/',function (req,res){//redirects anypage other than homepage to homepage.
   res.sendFile(__dirname+'/upload.html');
});

app.get('/',function (req,res){
   res.sendFile(__dirname+'/upload.html');
});

app.post('/file_upload', function (req, res) {
   upload1(req, res, function (err) {//to handle errors,middleware generated by multer
    if (err) {
      // if error occured, when uploading
      //console.log(err);
      res.send("Error,Maximum Upload size is intentionally set to 1mb");
    }
    else{
        var obj={
            Name:req.file.originalname,
            Mimetype:req.file.mimetype,
            Size:req.file.size
        };
       res.json(obj);
    }
   });
  });

app.listen(app.get('port'));
